name = "BeeDeeDee"
uuid = "9bed6e46-0232-43fb-95ab-f63adf9bda0f"
authors = ["Brian Douglas <briandgls92@gmail.com>"]
version = "0.2.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
